### ISSUE TITLE
Sidebar doesn't exist when provider is mounted, setting sidebar-width to zero until interaction

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/kibo#5]
![CleanShot 2024-10-11 at 12 07 31@2x](https://github.com/user-attachments/assets/bfd3c08e-4eb5-42c5-a4fe-a9c2b8d16745)

**Comment by kpotter-m2** [comment]
doesn't seem to be fixed, still prevalent in the docs: https://www.kibo-ui.com/components/gantt
